// The hand-authored opening (levels 1-25): one new idea at a time, every layout written out in full.
// scripts/calibrate.js tunes only `moves` (or `time`) and the star thresholds of these records; layouts stay as written.
// Layout legend: '.' candy  '#' hole  'j'/'J' jelly (1/2 layers)  '1'-'5' frosting layers  'k' Sugar Cage
//   'o' Cocoa Creep  'b' Fuse Candy (meta.fuse)  'c' cherry  'h' hazelnut  'x' exit tray  'p'/'P' portal pair (meta.portals)
//   '>' '<' '^' 'v' Sugar Belt. meta.preset: digits fix a starting candy color ('.' = random). meta.specials: pre-placed specials.
'use strict';

const FULL7 = ['.......', '.......', '.......', '.......', '.......', '.......', '.......'];
const FULL8 = ['........', '........', '........', '........', '........', '........', '........', '........'];

module.exports = [
  {
    id: 1, name: 'Sugar Start', role: 'tutorial', moves: 15, colors: 4, seed: 1001, rows: 7, cols: 7,
    layout: FULL7.slice(),
    goals: [{ type: 'collect', color: 2, count: 14 }],
    newMechanic: 'collect',
    tutorial: 'Swap two neighboring candies to make a row of three! Collect the candies shown at the top.',
    tip: 'Follow the glowing candies: tap one, then its neighbor, or just swipe.',
  },
  {
    id: 2, name: 'Berry Basket', role: 'tutorial', moves: 18, colors: 4, palette: [0, 4, 1, 3], seed: 2002, rows: 8, cols: 8,
    layout: ['#......#', '........', '........', '........', '........', '........', '........', '#......#'],
    goals: [{ type: 'collect', color: 0, count: 20 }, { type: 'collect', color: 4, count: 20 }],
    newMechanic: null,
    tutorial: 'Two kinds of candy on your list now. Every one you clear counts!',
    tip: 'Cherry beans and blueberry balls are on your list today.',
  },
  {
    id: 3, name: 'Stripe School', role: 'tutorial', moves: 15, colors: 4, seed: 3003, rows: 7, cols: 7,
    layout: FULL7.slice(),
    meta: { preset: ['.......', '.......', '...0...', '.0010..', '.......', '.......', '.......'] },
    goals: [{ type: 'collect', color: 0, count: 18 }],
    newMechanic: 'striped',
    tutorial: 'Line up FOUR candies to make a Striped candy. Match it to clear a whole row or column!',
    tip: 'Watch: four in a row become a striped candy.',
  },
  {
    id: 4, name: 'Stripe Practice', role: 'normal', moves: 20, colors: 4, seed: 4004, rows: 8, cols: 8,
    layout: ['.#....#.', '........', '........', '........', '........', '........', '........', '.#....#.'],
    goals: [{ type: 'collect', color: 3, count: 24 }],
    newMechanic: null,
    tip: 'Fire a striped candy along a long row to clear lots at once.',
  },
  {
    id: 5, name: 'Jelly Jar', role: 'tutorial', moves: 18, colors: 4, seed: 5005, rows: 8, cols: 8,
    layout: ['........', '.jjjjjj.', '.jjjjjj.', '..jjjj..', '..jjjj..', '.jjjjjj.', '.jjjjjj.', '........'],
    goals: [{ type: 'jelly' }],
    newMechanic: 'jelly',
    tutorial: 'Jelly sits under some candies. Make matches on top of it to wipe it all away!',
    tip: 'Clear every jelly square to win.',
  },
  {
    id: 6, name: 'Jelly Rows', role: 'normal', moves: 22, colors: 4, seed: 6006, rows: 8, cols: 8,
    layout: ['........', 'jjjjjjjj', '........', 'jjjjjjjj', '........', '........', 'jjjjjjjj', '........'],
    goals: [{ type: 'jelly' }],
    newMechanic: null,
    tip: 'Striped candies sweep a jelly row in one go.',
  },
  {
    id: 7, name: 'Wrap It Up', role: 'tutorial', moves: 22, colors: 5, seed: 7007, rows: 8, cols: 8,
    layout: FULL8.slice(),
    meta: { preset: ['........', '........', '........', '...2....', '...2....', '.2202...', '........', '........'] },
    goals: [{ type: 'collect', color: 2, count: 28 }],
    newMechanic: 'wrapped',
    tutorial: 'Make an L or T shape to create a Wrapped candy. It explodes twice!',
    tip: 'Slide the lemon into the corner of the L.',
  },
  {
    id: 8, name: 'Bow Practice', role: 'normal', moves: 22, colors: 5, seed: 8008, rows: 9, cols: 9,
    layout: ['###...###', '##.....##', '#.......#', '.........', '.........', '.........', '#.......#', '##.....##', '###...###'],
    goals: [{ type: 'collect', color: 4, count: 20 }, { type: 'collect', color: 2, count: 20 }],
    newMechanic: null,
    tip: 'Wrapped candies love the middle of the board.',
  },
  {
    id: 9, name: 'Cherry Drop', role: 'tutorial', moves: 20, colors: 4, seed: 9009, rows: 8, cols: 8,
    layout: ['..c..c..', '........', '........', '........', '........', '........', '........', 'xxxxxxxx'],
    goals: [{ type: 'ingredients', count: 2 }],
    newMechanic: 'ingredients',
    tutorial: 'Clear the candies under the cherries to drop them into the trays at the bottom.',
    tip: 'Matches below a cherry make it fall faster.',
  },
  {
    id: 10, name: 'Cherry Hill', role: 'breather', moves: 24, colors: 4, seed: 10010, rows: 8, cols: 8,
    layout: ['#c..c.c#', '........', '........', '........', '........', '........', '........', 'xxxxxxxx'],
    goals: [{ type: 'ingredients', count: 3 }],
    newMechanic: null,
    tip: 'Three cherries, lots of moves. Enjoy the ride!',
  },
  {
    id: 11, name: 'Rainbow Maker', role: 'tutorial', moves: 22, colors: 5, seed: 11011, rows: 8, cols: 8,
    layout: FULL8.slice(),
    meta: { preset: ['........', '........', '........', '........', '........', '..3.....', '33133...', '........'] },
    goals: [{ type: 'collect', color: 3, count: 32 }],
    newMechanic: 'bomb',
    tutorial: 'Line up FIVE to make a Color Bomb. Swap it with a candy to clear every candy of that color!',
    tip: 'Drop the green square into the gap to line up five.',
  },
  {
    id: 12, name: 'Special Orders', role: 'tutorial', moves: 25, colors: 5, seed: 12012, rows: 8, cols: 8,
    layout: ['........', '........', '........', '...##...', '...##...', '........', '........', '........'],
    goals: [{ type: 'order', item: 'striped', count: 2 }, { type: 'order', item: 'wrapped', count: 1 }],
    newMechanic: 'order',
    tutorial: 'Candy orders ask for special candies. Make them and fire them to fill the order!',
    tip: 'A striped candy counts when it goes off.',
  },
  {
    id: 13, name: 'Frosting Fields', role: 'tutorial', moves: 22, colors: 5, seed: 13013, rows: 8, cols: 8,
    layout: ['........', '........', '.1....1.', '..1..1..', '........', '..1..1..', '.1....1.', '........'],
    goals: [{ type: 'order', item: 'frosting', count: 8 }],
    newMechanic: 'frosting',
    tutorial: 'Frosting blocks a cell. Make a match right next to it to crack it away.',
    tip: 'Blasts from special candies crack frosting too.',
  },
  {
    id: 14, name: 'Frosted Jelly', role: 'normal', moves: 26, colors: 5, seed: 14014, rows: 9, cols: 9,
    layout: ['.........', '.jjjjjjj.', '.j1...1j.', '.j.....j.', '.j..1..j.', '.j.....j.', '.j1...1j.', '.jjjjjjj.', '.........'],
    goals: [{ type: 'jelly' }],
    newMechanic: null,
    tip: 'Work the jelly ring from the inside out.',
  },
  {
    id: 15, name: 'Double Jelly', role: 'tutorial', moves: 26, colors: 5, seed: 15015, rows: 8, cols: 8,
    layout: ['........', '.JJJJJJ.', '.J....J.', '.J....J.', '.J....J.', '.J....J.', '.JJJJJJ.', '........'],
    goals: [{ type: 'jelly' }],
    newMechanic: 'jelly2',
    tutorial: 'Thick jelly needs two clears: match on it twice.',
    tip: 'Wrapped candies hit the same cells twice. Handy!',
  },
  {
    id: 16, name: 'Combo Lab', role: 'tutorial', moves: 18, colors: 5, seed: 16016, rows: 8, cols: 8,
    layout: FULL8.slice(),
    meta: { specials: [{ at: [6, 2], special: 'stripe_row' }, { at: [6, 3], special: 'wrapped' }, { at: [2, 5], special: 'stripe_col' }, { at: [2, 6], special: 'stripe_row' }] },
    goals: [{ type: 'collect', color: 4, count: 34 }],
    newMechanic: 'combos',
    tutorial: 'Swap two special candies together for a giant combo!',
    tip: 'Striped + wrapped clears three rows and three columns.',
  },
  {
    id: 17, name: 'Beat the Clock', role: 'tutorial', time: 60, colors: 5, seed: 17017, rows: 8, cols: 8,
    layout: FULL8.slice(),
    goals: [{ type: 'collect', color: 2, count: 40 }],
    newMechanic: 'timed',
    tutorial: 'A timed level! Collect the candies before the clock runs out. Every special candy adds 2 seconds.',
    tip: 'Quick matches first, think later!',
  },
  {
    id: 18, name: 'Quick Treats', role: 'breather', time: 60, colors: 5, seed: 18018, rows: 8, cols: 8,
    layout: ['#......#', '........', '........', '........', '........', '........', '........', '#......#'],
    goals: [{ type: 'collect', color: 0, count: 28 }],
    newMechanic: null,
    tip: 'Plenty of time. Go for specials!',
  },
  {
    id: 19, name: 'Sugar Cages', role: 'tutorial', moves: 22, colors: 5, seed: 19019, rows: 8, cols: 8,
    layout: ['........', '........', '..k..k..', '...kk...', '...kk...', '..k..k..', '........', '........'],
    goals: [{ type: 'collect', color: 1, count: 28 }],
    newMechanic: 'cage',
    tutorial: "Caged candies can't move. Match them, or blast them, to break the cage.",
    tip: 'A caged candy still counts in a match.',
  },
  {
    id: 20, name: 'Caged Jelly', role: 'normal', moves: 24, colors: 5, seed: 20020, rows: 8, cols: 8,
    layout: ['........', '.jjjjjj.', '.jk..kj.', '.j....j.', '.j....j.', '.jk..kj.', '.jjjjjj.', '........'],
    goals: [{ type: 'jelly' }],
    newMechanic: null,
    tip: 'Free the cages first, then sweep the jelly.',
  },
  {
    id: 21, name: 'Portal Party', role: 'tutorial', moves: 22, colors: 5, seed: 21021, rows: 9, cols: 9,
    layout: ['.........', '.........', '.........', 'p.p.p.p.p', '#########', '##PPPPP##', '##.....##', '##.....##', '##.....##'],
    meta: { portals: [{ in: [3, 0], out: [5, 2] }, { in: [3, 2], out: [5, 3] }, { in: [3, 4], out: [5, 4] }, { in: [3, 6], out: [5, 5] }, { in: [3, 8], out: [5, 6] }] },
    goals: [{ type: 'collect', color: 3, count: 22 }],
    newMechanic: 'portals',
    tutorial: 'Candies that fall into a portal pop out of its partner below.',
    tip: 'Matches up top keep the lower garden supplied.',
  },
  {
    id: 22, name: 'Cocoa Creep', role: 'tutorial', moves: 22, colors: 5, seed: 22022, rows: 8, cols: 8,
    layout: ['........', '........', '........', '...oo...', '........', '........', '........', '........'],
    goals: [{ type: 'collect', color: 1, count: 30 }],
    newMechanic: 'cocoa',
    tutorial: "Cocoa spreads after any move that doesn't clear some. Match next to it to clean it up!",
    tip: 'Keep the cocoa in check every few moves.',
  },
  {
    id: 23, name: 'Cocoa Cleanup', role: 'normal', moves: 24, colors: 5, seed: 23023, rows: 8, cols: 8,
    layout: ['........', '.o....o.', '........', '........', '........', '........', '.o....o.', '........'],
    goals: [{ type: 'collect', color: 4, count: 32 }],
    newMechanic: null,
    tip: 'Collect the blue balls, but tidy the cocoa as you go.',
  },
  {
    id: 24, name: 'Fuse Box', role: 'tutorial', moves: 22, colors: 5, seed: 24024, rows: 8, cols: 8,
    layout: ['........', '........', '..b..b..', '........', '........', '........', '........', '........'],
    meta: { fuse: 16 },
    goals: [{ type: 'collect', color: 4, count: 27 }],
    newMechanic: 'fuse',
    tutorial: 'Fuse Candies count down after every move. Clear them before they reach zero!',
    tip: 'Match a fuse candy, or blast it, to defuse it.',
  },
  {
    id: 25, name: 'Sweet Summit', role: 'normal', moves: 28, colors: 5, seed: 25025, rows: 9, cols: 9,
    layout: ['...c.c...', '.........', '.2.....2.', '..jjjjj..', '..j...j..', '..jjjjj..', '.2.....2.', '.........', 'xxxxxxxxx'],
    goals: [{ type: 'jelly' }, { type: 'ingredients', count: 2 }],
    newMechanic: null,
    tip: 'Two goals at once: jelly and cherries. You know all the tricks!',
  },
];
